[package]
name = "quick-error"
description = """
    A macro which makes error types pleasant to write.
"""
license = "MIT"
version = "0.2.0"
keywords = ["macro", "error", "type", "enum"]
authors = ["Paul Colomiets <paul@colomiets.name>"]
homepage = "http://github.com/tailhook/quick-error"
repository = "http://github.com/tailhook/quick-error"
documentation = "http://tailhook.github.io/quick-error/"
